
	hey just checking in on ya. drinks tonight/tomo?

- Hi hi! Can we do something post holidays? I have an opposition due dec. 29 :/
-	Which I want to finish before Christmas, so I can go home. 

wow, good luck with that. I'm sure you'll make it amazing.

not sure where your head is at re us. for now I'll assume we're not together, but if you want to revisit after the holidays I would love to see you.

- Yeah I wanted to talk. I'm sorry it hasn't worked out. 
- I want to see you 
- I have felt really good and calm over the last 6 ish weeks

that's great, I'm so glad 

that you've felt that way 

I want to see you too 

I've missed you 

it seems like maybe now isn't the right time for you 

- I have missed you too and spent a lot of time thinking about you.

I know 

but there's a difference between having feelings for someone and being ready to be with them 

- I know.

I want to be with you but only if you want to be with me 

and only when you're ready to really be in it 

there are so many things I appreciate about you

someday I would love to tell you what they are 

I still have your contact lenses on my nightstand and your pen in my medicine cabinet

but I'm not going to just wait around for you 

how are you thinking about all this? 

- Well, I think this is an in-person conversation. But I don't want or expect you to wait around for me.
- And I'm sad that that's where I am right now, because I think you are really great.
- I also feel like I was never really my best to or with you, because of some sort of hesitation
- So while its nice to read that you appreciate so many things about me, my first response is, how can that be? Since I don't love who I was during that time
- A little on edge, stressy, ugh. I am sorry. 

I know, I felt that hesitation too 

- I appreciate many things about YOU.

well when I see you I'll tell you all the things about you and give you time to cross-examine 

but they are the things that came through even when you were stressed out 

- I felt like I didn't laugh at things I would normally laugh at.
- Like, I think about things that I didn't laugh at and think, wait, that's funny, and ordinarily I would laugh at that!
- I was bottled up though and it made me not as good 

wow
 
then I would love to see you at your best  

- I was just so caged and not open and I think it must have been hard for you.
- When you are like that emotionally I think it seeps into everything, like laughter 
- Anyway, I am going to bed 
- But let's get together in 2016.

yes, let's 

and if at some point you're ready to be with me and be fully present in the relationship, you know I'm up for it

goodnight rainchaser 

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='../css/iphone.css ' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t

