* Cocktails on Saint Marks 
http://drinkboston.com/wp-content/uploads/2009/09/early1900s-bartender.jpg 
Since it seems that everyone has their own plans for later in the evening, I'll be having people over for early cocktails on Saint Marks so we can all be together as a family one last time before 2015 takes its final bow. 

Nota bene, this is not a New Year's party but a pre-New-Years pre-party. We'll be gathering at the unfashionably early hour of 5:00pm to toast the year ahead before adjourning promptly at 8:00 and scattering across the boroughs. 

The house will offer a limited menu of cocktails of gin, mezcal, and moonshine. Your own civilian contributions of spirits and snacks are also welcome but by no means required. Your friends are also welcome.

Looking forward to seeing you all. 

Until then!

Jay

*Where*: [[https://goo.gl/maps/deaqUaSuWNA2][22 Saint Marks Place Apt. D New York NY 10003]] 
*Map*: https://goo.gl/maps/deaqUaSuWNA2 
*When*: 5:00pm today 

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://dixit.ca/css/gmail.css' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
 
