* first draft 

#+BEGIN_EXAMPLE
As 2016 lifts off and ascends toward its cruising altitude, I want to make sure you're all ______ (fill in the blank, I need a suggestion). Consequently, I've decided to gather some friends together for early cocktails this Friday. 

I'll be co-hosting this party with a friend, the brilliant Max Makewell, at his art studio in Gramercy, and we'll be convening early, at 6:00pm, to toast the new year amid Max's spooky and mythic Rorschach-like paintings before disbanding at 10:00pm to forge off into the weekend as individuals once again. 

The house will offer light snacks and a festive menu of cold-weather cocktails to warm your seasonally-affected bones, including drinks of gin, mezcal, and moonshine. Your own civilian contributions of booze and foodstuffs are also welcome but by no means required. Please feel free to invite friends as well.

Looking forward to seeing you all.

Until then!

Jay 
#+END_EXAMPLE

* second draft
#+BEGIN_EXAMPLE
As winter rouses and shakes off its slumber, I've decided to gather friends together this Friday at 6:00pm for some cold-weather cocktails to warm our bones and lift our seasonally-affected spirits. 

I'll be co-hosting with a friend, the brilliant Max Makewell, at his art studio in Gramercy, where we'll clink glasses amid his mythic, kaleidoscopic paintings and toast the possibilities of the year ahead. 

The house will offer light snacks and festive cocktails of gin, mezcal, and moonshine. Your own civilian contributions of booze and foodstuffs are also welcome but by no means required. Please feel free to invite friends as well.

Looking forward to seeing you all.

Until then!

Jay 
#+END_EXAMPLE

* Conversation
dixit.ca/art

what do you think?

- It's great!
- Very stylish and breezy

aww thank you!

any edits? 

- Nah it's great as is
- You know how adorable I think it is when people other than me make metaphors 

but for me it’s harder 

what's the metaphor? winter as a great sleeping beast? 

- Yeah
- Your first draft was something different

did you see my first draft? it was awful 

- Cruising altitude 
- Yes

“As 2016 lifts off and ascends toward cruising altitude” 

it made no sense 

- Yes it's better now 

yeah definitely. thanks!!

how's this? 

As winter rouses and shakes off its slumber, I've decided to gather friends together this Friday at 6:00pm for some cold-weather cocktails to lift our seasonally-affected spirits as we lurch into the new year.

(I added "as we lurch into the new year") 

- A little wordy now. 

k 

better? As winter rouses and shakes off its slumber, I'm assembling friends this Friday at 6:00pm for cold-weather cocktails to lift our seasonally-affected spirits as we lurch into the new year. 

As winter rouses and shakes off its slumber, I'm gathering friends together this Friday at 6:00pm for cold-weather cocktails to lift our seasonally-affected spirits as we lurch into the new year. 

- Try this: 
- "As winter rouses and shakes off its slumber, let's gather for some cold weather cocktails to lift our...

much better 

- The problem is you don't want two "as" phrases in the same sentence 
- Also: no need to include the logistical info in the cute opener 
- Just move that to another sentence 

As winter rouses and shakes off its slumber, let's gather together for cold-weather cocktails to lift our seasonally-affected spirits as we lurch into the new year. 

- Try this:

K 

- As winter rouses and shakes off its slumber and we lurch into the new year...

Combine the as phrases?

ohh 

Now that winter has finally roused and shaken off its slumber, let's gather together for cold-weather cocktails to lift our seasonally-affected spirits as we lurch into the new year. 

- Ok better

Now that winter has finally roused and shaken off its slumber, let's gather together for cold-weather cocktails to lift our seasonally-affected spirits as we lurch forward into the new year. 

need a better word than "cold-weather" 

that's kinda describing what's it's for, not what it is 

i.e. "warm cocktails" communicates the idea better than "cold-weather cocktails"

but they're not warm 

so what's a word or idea that communicates "this cocktail will lift your spirits"? 

- You don't need anything there really 

I'd like something? 

rhythmically I feel like the sentence wants a detail about what kind of cocktails they are 

festive? 

Now that winter has finally roused and shaken off its slumber, let's gather together for some festive cocktails to lift our seasonally-affected spirits as we lurch forth into the new year. 

- Nah

you see what I'm going for though? 

- I suppose you need something that means warming

right. or one that means lifting 

- Revitalizing 

nice

- Or

Ok

or? 

- I don't know I was trying to think of something 

reviving 

- Restorative 

better 

Now that winter has finally roused and shaken off its slumber, let's gather together for cocktails to revitalize us and lift our seasonally-affected spirits as we lurch forth into the new year. 

ohh

get rid of lift

Now that winter has finally roused and shaken off its slumber, let's gather together for cocktails to revitalize our seasonally-affected spirits as we lurch forth into the new year. 

but now revitalize doesn't work 

verb for ____ your spirits, not lift 

something like revitalize, but that can take "our spirits" as an object

- Haha now you're circling back to what I said
- Why can't spirits be revitalized?
- Brought back to life?

I don't know, doesn't make sense to me

- Is that your problem with it?

your spirits are down, not dead 

- OK
- Then do lift, silly!

Hahaha

restore even 

gladden? 

Quicken?

- Gladden maybe if that sounds right to you

as always, let me look it up in the dictionary and see 

you don't like quicken? 

revive?

resurrect? 

- Which basically means the same thing as revitalize 

yup 

- Ha even further down that path

true

"revive and gladden"? 

- Sounds good

!

thanks!

further down, I have "festive cocktails" 

I can change it 

how about "unusual cocktails"? 

The house will offer a small menu of unusual cocktails of gin, mezcal, and moonshine, as well as light snacks. 

- I mean will they be unusual??

sure, they could be 

all we have to do is make one drink of mescal and pineapple juice or whatever 

and that qualifies

- OK old sport

at mine I made tequila and watermelon smoothie, that's unusual!

really the question is, does "unusual cocktails" sound intriguing? 

I think it does 

- We should definitely let the sentence dictate the offerings 

hahaha!

writers to the core 

:-) 

- :)

let the marketing dictate the features 

- Right 
- So go for it!

great! last question 

- If it were my party I would tell everyone this story as I served up the pineapple and mezcal cocktail

"mythic, kaleidoscopic paintings"

oh believe me, we will! 

this conversation is going to go down in the annals of editing history 

- :)

last question: what do you think of "mythic, kaleidoscopic paintings"

- Are they actually mythic and kaleidoscopic?!?!?
- Or are you going to have to commission some new paintings for the purposes of this sentence?

hahaha 

http://i.imgur.com/xsQD9hS.jpg 


- Sounds about right!

thank you so much!!

- YW 

you're a good editor Hood 

- Gracias 

:-)

hey you know in those old Gothic novels, when people got "consumption" i.e. TB? 

and they went to hot springs to get better? what adjective did they use to describe those hot springs.

- Hahahaha
- I have no idea 

that's the adjective I need!

Google: "tuberculosis consumption hot springs"

- I feel like restorative 

curative? 

therapeutic? 

- Sure

K!


* final draft 

#+BEGIN_EXAMPLE 
Now that winter has at last roused and shaken off its slumber, let's gather together for some healing cocktails to revive our seasonally-affected spirits as we lurch forward into the new year. 

I'll be co-hosting with a friend, the brilliant Max Makewell, at his art studio in Gramercy, where we'll clink glasses amid his mythic, kaleidoscopic paintings and toast the possibilities of the year ahead. 

The house will offer a small menu of unusual cocktails of gin, mezcal, and moonshine, as well as light snacks. Your own civilian contributions of booze and foodstuffs are likewise welcome but certainly not required. Please feel free to invite friends as well.

Looking forward to seeing you all.

Until then!

Jay 
#+END_EXAMPLE 

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://incandescentman.github.io/css/iphone-css-better.css' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t 
