I was born a gentleman, though I have been nothing but a
poor traveling trader and hunter all my life. Whether I have remained
so I know not, you must judge of that. Heaven knows I've tried. I have
killed many men in my time, yet I have never slain wantonly or stained
my hand in innocent blood, but only in self-defence. The Almighty gave
us our lives, and I suppose He meant us to defend them, at least I have
always acted on that, and I hope it will not be brought up against me
when my clock strikes. There, there, it is a cruel and a wicked world,
and for a timid man I have been mixed up in a great deal of fighting. I
cannot tell the rights of it, but at any rate I have never stolen,
though once I cheated a Kafir out of a herd of cattle. But then he had
done me a dirty turn, and it has troubled me ever since into the
bargain.


Well, it is eighteen months or so ago since first I met Sir Henry
Curtis and Captain Good. It was in this way. I had been up elephant
hunting beyond Bamangwato, and had met with bad luck. Everything went
wrong that trip, and to top up with I got the fever badly. So soon as I
was well enough I trekked down to the Diamond Fields, sold such ivory
as I had, together with my wagon and oxen, discharged my hunters, and
took the post-cart to the Cape. After spending a week in Cape Town,
finding that they overcharged me at the hotel, and having seen
everything there was to see, including the botanical gardens, which
seem to me likely to confer a great benefit on the country, and the new
Houses of Parliament, which I expect will do nothing of the sort, I
determined to go back to Natal by the _Dunkeld_, then lying at the
docks waiting for the _Edinburgh Castle_ due in from England. I took my
berth and went aboard, and that afternoon the Natal passengers from the
_Edinburgh Castle_ transhipped, and we weighed and put to sea.

Among these passengers who came on board were two who excited my
curiosity. One, a gentleman of about thirty, was perhaps the
biggest-chested and longest-armed man I ever saw. He had yellow hair, a
thick yellow beard, clear-cut features, and large grey eyes set deep in
his head. I never saw a finer-looking man, and somehow he reminded me
of an ancient Dane. Not that I know much of ancient Danes, though I
knew a modern Dane who did me out of ten pounds; but I remember once
seeing a picture of some of those gentry, who, I take it, were a kind
of white Zulus. They were drinking out of big horns, and their long
hair hung down their backs. As I looked at my friend standing there by
the companion-ladder, I thought that if he only let his grow a little,
put one of those chain shirts on to his great shoulders, and took hold
of a battle-axe and a horn mug, he might have sat as a model for that
picture. And by the way it is a curious thing, and just shows how the
blood will out, I discovered afterwards that Sir Henry Curtis, for that
was the big man's name, is of Danish blood. He also reminded me
strongly of somebody else, but at the time I could not remember who it
was.

The other man, who stood talking to Sir Henry, was stout and dark, and
of quite a different cut. I suspected at once that he was a naval
officer; I don't know why, but it is difficult to mistake a navy man. I
have gone shooting trips with several of them in the course of my life,
and they have always proved themselves the best and bravest and nicest
fellows I ever met, though sadly given, some of them, to the use of
profane language. I asked a page or two back, what is a gentleman? I'll
answer the question now: A Royal Naval officer is, in a general sort of
way, though of course there may be a black sheep among them here and
there. I fancy it is just the wide seas and the breath of God's winds
that wash their hearts and blow the bitterness out of their minds and
make them what men ought to be.

Well, to return, I proved right again; I ascertained that the dark man
_was_ a naval officer, a lieutenant of thirty-one, who, after seventeen
years' service, had been turned out of her Majesty's employ with the
barren honour of a commander's rank, because it was impossible that he
should be promoted. This is what people who serve the Queen have to
expect: to be shot out into the cold world to find a living just when
they are beginning really to understand their work, and to reach the
prime of life. I suppose they don't mind it, but for my own part I had
rather earn my bread as a hunter. One's halfpence are as scarce
perhaps, but you do not get so many kicks.

The officer's name I found out--by referring to the passengers'
lists--was Good--Captain John Good. He was broad, of medium height,
dark, stout, and rather a curious man to look at. He was so very neat
and so very clean-shaved, and he always wore an eye-glass in his right
eye. It seemed to grow there, for it had no string, and he never took
it out except to wipe it. At first I thought he used to sleep in it,
but afterwards I found that this was a mistake. He put it in his
trousers pocket when he went to bed, together with his false teeth, of
which he had two beautiful sets that, my own being none of the best,
have often caused me to break the tenth commandment. But I am
anticipating.

Soon after we had got under way evening closed in, and brought with it
very dirty weather. A keen breeze sprung up off land, and a kind of
aggravated Scotch mist soon drove everybody from the deck. As for the
_Dunkeld_, she is a flat-bottomed punt, and going up light as she was,
she rolled very heavily. It almost seemed as though she would go right
over, but she never did. It was quite impossible to walk about, so I
stood near the engines where it was warm, and amused myself with
watching the pendulum, which was fixed opposite to me, swinging slowly
backwards and forwards as the vessel rolled, and marking the angle she
touched at each lurch.

"That pendulum's wrong; it is not properly weighted," suddenly said a
somewhat testy voice at my shoulder. Looking round I saw the naval
officer whom I had noticed when the passengers came aboard.

"Indeed, now what makes you think so?" I asked.

"Think so. I don't think at all. Why there"--as she righted herself
after a roll--"if the ship had really rolled to the degree that thing
pointed to, then she would never have rolled again, that's all. But it
is just like these merchant skippers, they are always so confoundedly
careless."

Just then the dinner-bell rang, and I was not sorry, for it is a
dreadful thing to have to listen to an officer of the Royal Navy when
he gets on to that subject. I only know one worse thing, and that is to
hear a merchant skipper express his candid opinion of officers of the
Royal Navy.

Captain Good and I went down to dinner together, and there we found Sir
Henry Curtis already seated. He and Captain Good were placed together,
and I sat opposite to them. The captain and I soon fell into talk about
shooting and what not; he asking me many questions, for he is very
inquisitive about all sorts of things, and I answering them as well as
I could. Presently he got on to elephants.

"Ah, sir," called out somebody who was sitting near me, "you've reached
the right man for that; Hunter Quatermain should be able to tell you
about elephants if anybody can."

Sir Henry, who had been sitting quite quiet listening to our talk,
started visibly.

"Excuse me, sir," he said, leaning forward across the table, and
speaking in a low deep voice, a very suitable voice, it seemed to me,
to come out of those great lungs. "Excuse me, sir, but is your name
Allan Quatermain?"

I said that it was.

The big man made no further remark, but I heard him mutter "fortunate"
into his beard.

Presently dinner came to an end, and as we were leaving the saloon Sir
Henry strolled up and asked me if I would come into his cabin to smoke
a pipe. I accepted, and he led the way to the _Dunkeld_ deck cabin, and
a very good cabin it is. It had been two cabins, but when Sir Garnet
Wolseley or one of those big swells went down the coast in the
_Dunkeld_, they knocked away the partition and have never put it up
again. There was a sofa in the cabin, and a little table in front of
it. Sir Henry sent the steward for a bottle of whisky, and the three of
us sat down and lit our pipes.

"Mr. Quatermain," said Sir Henry Curtis, when the man had brought the
whisky and lit the lamp, "the year before last about this time, you
were, I believe, at a place called Bamangwato, to the north of the
Transvaal."

"I was," I answered, rather surprised that this gentleman should be so
well acquainted with my movements, which were not, so far as I was
aware, considered of general interest.

"You were trading there, were you not?" put in Captain Good, in his
quick way.

"I was. I took up a wagon-load of goods, made a camp outside the
settlement, and stopped till I had sold them."

Sir Henry was sitting opposite to me in a Madeira chair, his arms
leaning on the table. He now looked up, fixing his large grey eyes full
upon my face. There was a curious anxiety in them, I thought.

"Did you happen to meet a man called Neville there?"

"Oh, yes; he outspanned alongside of me for a fortnight to rest his
oxen before going on to the interior. I had a letter from a lawyer a
few months back, asking me if I knew what had become of him, which I
answered to the best of my ability at the time."

"Yes," said Sir Henry, "your letter was forwarded to me. You said in it
that the gentleman called Neville left Bamangwato at the beginning of
May in a wagon with a driver, a voorlooper, and a Kafir hunter called
Jim, announcing his intention of trekking if possible as far as Inyati,
the extreme trading post in the Matabele country, where he would sell
his wagon and proceed on foot. You also said that he did sell his
wagon, for six months afterwards you saw the wagon in the possession of
a Portuguese trader, who told you that he had bought it at Inyati from
a white man whose name he had forgotten, and that he believed the white
man with the native servant had started off for the interior on a
shooting trip."

"Yes."

Then came a pause.

"Mr. Quatermain," said Sir Henry suddenly, "I suppose you know or can
guess nothing more of the reasons of my--of Mr. Neville's journey to
the northward, or as to what point that journey was directed?"

"I heard something," I answered, and stopped. The subject was one which
I did not care to discuss.

Sir Henry and Captain Good looked at each other, and Captain Good
nodded.

"Mr. Quatermain," went on the former, "I am going to tell you a story,
and ask your advice, and perhaps your assistance. The agent who
forwarded me your letter told me that I might rely on it implicitly, as
you were," he said, "well known and universally respected in Natal, and
especially noted for your discretion."

I bowed and drank some whisky and water to hide my confusion, for I am
a modest man--and Sir Henry went on.

"Mr. Neville was my brother."

"Oh," I said, starting, for now I knew of whom Sir Henry had reminded
me when first I saw him. His brother was a much smaller man and had a
dark beard, but now that I thought of it, he possessed eyes of the same
shade of grey and with the same keen look in them: the features too
were not unlike.

"He was," went on Sir Henry, "my only and younger brother, and till
five years ago I do not suppose that we were ever a month away from
each other. But just about five years ago a misfortune befell us, as
sometimes does happen in families. We quarrelled bitterly, and I
behaved unjustly to my brother in my anger."

Here Captain Good nodded his head vigorously to himself. The ship gave
a big roll just then, so that the looking-glass, which was fixed
opposite us to starboard, was for a moment nearly over our heads, and
as I was sitting with my hands in my pockets and staring upwards, I
could see him nodding like anything.

"As I daresay you know," went on Sir Henry, "if a man dies intestate,
and has no property but land, real property it is called in England, it
all descends to his eldest son. It so happened that just at the time
when we quarrelled our father died intestate. He had put off making his
will until it was too late. The result was that my brother, who had not
been brought up to any profession, was left without a penny. Of course
it would have been my duty to provide for him, but at the time the
quarrel between us was so bitter that I did not--to my shame I say it
(and he sighed deeply)--offer to do anything. It was not that I grudged
him justice, but I waited for him to make advances, and he made none. I
am sorry to trouble you with all this, Mr. Quatermain, but I must to
make things clear, eh, Good?"

"Quite so, quite so," said the captain. "Mr. Quatermain will, I am
sure, keep this history to himself."

"Of course," said I, for I rather pride myself on my discretion, for
which, as Sir Henry had heard, I have some repute.

"Well," went on Sir Henry, "my brother had a few hundred pounds to his
account at the time. Without saying anything to me he drew out this
paltry sum, and, having adopted the name of Neville, started off for
South Africa in the wild hope of making a fortune. This I learned
afterwards. Some three years passed, and I heard nothing of my brother,
though I wrote several times. Doubtless the letters never reached him.
But as time went on I grew more and more troubled about him. I found
out, Mr. Quatermain, that blood is thicker than water."

"That's true," said I, thinking of my boy Harry.

"I found out, Mr. Quatermain, that I would have given half my fortune
to know that my brother George, the only relation I possess, was safe
and well, and that I should see him again."

"But you never did, Curtis," jerked out Captain Good, glancing at the
big man's face.

"Well, Mr. Quatermain, as time went on I became more and more anxious
to find out if my brother was alive or dead, and if alive to get him
home again. I set enquiries on foot, and your letter was one of the
results. So far as it went it was satisfactory, for it showed that till
lately George was alive, but it did not go far enough. So, to cut a
long story short, I made up my mind to come out and look for him
myself, and Captain Good was so kind as to come with me."

"Yes," said the captain; "nothing else to do, you see. Turned out by my
Lords of the Admiralty to starve on half pay. And now perhaps, sir, you
will tell us what you know or have heard of the gentleman called
Neville."




CHAPTER II

THE LEGEND OF SOLOMON'S MINES

"What was it that you heard about my brother's journey at Bamangwato?"
asked Sir Henry, as I paused to fill my pipe before replying to Captain
Good.

"I heard this," I answered, "and I have never mentioned it to a soul
till to-day. I heard that he was starting for Solomon's Mines."

"Solomon's Mines?" ejaculated both my hearers at once. "Where are they?"

"I don't know," I said; "I know where they are said to be. Once I saw
the peaks of the mountains that border them, but there were a hundred
and thirty miles of desert between me and them, and I am not aware that
any white man ever got across it save one. But perhaps the best thing I
can do is to tell you the legend of Solomon's Mines as I know it, you
passing your word not to reveal anything I tell you without my
permission. Do you agree to that? I have my reasons for asking."

Sir Henry nodded, and Captain Good replied, "Certainly, certainly."

"Well," I began, "as you may guess, generally speaking, elephant
hunters are a rough set of men, who do not trouble themselves with much
beyond the facts of life and the ways of Kafirs. But here and there you
meet a man who takes the trouble to collect traditions from the
natives, and tries to make out a little piece of the history of this
dark land. It was such a man as this who first told me the legend of
Solomon's Mines, now a matter of nearly thirty years ago. That was when
I was on my first elephant hunt in the Matabele country. His name was
Evans, and he was killed the following year, poor fellow, by a wounded
buffalo, and lies buried near the Zambesi Falls. I was telling Evans
one night, I remember, of some wonderful workings I had found whilst
hunting koodoo and eland in what is now the Lydenburg district of the
Transvaal. I see they have come across these workings again lately in
prospecting for gold, but I knew of them years ago. There is a great
wide wagon road cut out of the solid rock, and leading to the mouth of
the working or gallery. Inside the mouth of this gallery are stacks of
gold quartz piled up ready for roasting, which shows that the workers,
whoever they were, must have left in a hurry. Also, about twenty paces
in, the gallery is built across, and a beautiful bit of masonry it is."

"'Ay,' said Evans, 'but I will spin you a queerer yarn than that'; and
he went on to tell me how he had found in the far interior a ruined
city, which he believed to be the Ophir of the Bible, and, by the way,
other more learned men have said the same long since poor Evans's time.
I was, I remember, listening open-eared to all these wonders, for I was
young at the time, and this story of an ancient civilisation and of the
treasures which those old Jewish or Phoenician adventurers used to
extract from a country long since lapsed into the darkest barbarism
took a great hold upon my imagination, when suddenly he said to me,
'Lad, did you ever hear of the Suliman Mountains up to the north-west
of the Mushakulumbwe country?' I told him I never had. 'Ah, well,' he
said, 'that is where Solomon really had his mines, his diamond mines, I
mean.'

"'How do you know that?' I asked.

"'Know it! why, what is "Suliman" but a corruption of Solomon? 
Besides, an old Isanusi or witch doctoress up in the Manica country
told me all about it. She said that the people who lived across those
mountains were a "branch" of the Zulus, speaking a dialect of Zulu, but
finer and bigger men even; that there lived among them great wizards,
who had learnt their art from white men when "all the world was dark,"
and who had the secret of a wonderful mine of "bright stones."'

"Well, I laughed at this story at the time, though it interested me,
for the Diamond Fields were not discovered then, but poor Evans went
off and was killed, and for twenty years I never thought any more of
the matter. However, just twenty years afterwards--and that is a long
time, gentlemen; an elephant hunter does not often live for twenty
years at his business--I heard something more definite about Suliman's
Mountains and the country which lies beyond them. I was up beyond the
Manica country, at a place called Sitanda's Kraal, and a miserable
place it was, for a man could get nothing to eat, and there was but
little game about. I had an attack of fever, and was in a bad way
generally, when one day a Portugee arrived with a single companion--a
half-breed. Now I know your low-class Delagoa Portugee well. There is
no greater devil unhung in a general way, battening as he does upon
human agony and flesh in the shape of slaves. But this was quite a
different type of man to the mean fellows whom I had been accustomed to
meet; indeed, in appearance he reminded me more of the polite doms I
have read about, for he was tall and thin, with large dark eyes and
curling grey mustachios. We talked together for a while, for he could
speak broken English, and I understood a little Portugee, and he told
me that his name was José Silvestre, and that he had a place near
Delagoa Bay. When he went on next day with his half-breed companion, he
said 'Good-bye,' taking off his hat quite in the old style.

"'Good-bye, senor,' he said; 'if ever we meet again I shall be the
richest man in the world, and I will remember you.' I laughed a
little--I was too weak to laugh much--and watched him strike out for
the great desert to the west, wondering if he was mad, or what he
thought he was going to find there.

"A week passed, and I got the better of my fever. One evening I was
sitting on the ground in front of the little tent I had with me,
chewing the last leg of a miserable fowl I had bought from a native for
a bit of cloth worth twenty fowls, and staring at the hot red sun
sinking down over the desert, when suddenly I saw a figure, apparently
that of a European, for it wore a coat, on the slope of the rising
ground opposite to me, about three hundred yards away. The figure crept
along on its hands and knees, then it got up and staggered forward a
few yards on its legs, only to fall and crawl again. Seeing that it
must be somebody in distress, I sent one of my hunters to help him, and
presently he arrived, and who do you suppose it turned out to be?"

"José Silvestre, of course," said Captain Good.

"Yes, José Silvestre, or rather his skeleton and a little skin. His
face was a bright yellow with bilious fever, and his large dark eyes
stood nearly out of his head, for all the flesh had gone. There was
nothing but yellow parchment-like skin, white hair, and the gaunt bones
sticking up beneath.

"'Water! for the sake of Christ, water!' he moaned and I saw that his
lips were cracked, and his tongue, which protruded between them, was
swollen and blackish.

"I gave him water with a little milk in it, and he drank it in great
gulps, two quarts or so, without stopping. I would not let him have any
more. Then the fever took him again, and he fell down and began to rave
about Suliman's Mountains, and the diamonds, and the desert. I carried
him into the tent and did what I could for him, which was little
enough; but I saw how it must end. About eleven o'clock he grew
quieter, and I lay down for a little rest and went to sleep. At dawn I
woke again, and in the half light saw Silvestre sitting up, a strange,
gaunt form, and gazing out towards the desert. Presently the first ray
of the sun shot right across the wide plain before us till it reached
the faraway crest of one of the tallest of the Suliman Mountains more
than a hundred miles away.

"'There it is!' cried the dying man in Portuguese, and pointing with
his long, thin arm, 'but I shall never reach it, never. No one will
ever reach it!'

"Suddenly, he paused, and seemed to take a resolution. 'Friend,' he
said, turning towards me, 'are you there? My eyes grow dark.'

"'Yes,' I said; 'yes, lie down now, and rest.'

"'Ay,' he answered, 'I shall rest soon, I have time to rest--all
eternity. Listen, I am dying! You have been good to me. I will give you
the writing. Perhaps you will get there if you can live to pass the
desert, which has killed my poor servant and me.'

"Then he groped in his shirt and brought out what I thought was a Boer
tobacco pouch made of the skin of the Swart-vet-pens or sable antelope.
It was fastened with a little strip of hide, what we call a rimpi, and
this he tried to loose, but could not. He handed it to me. 'Untie it,'
he said. I did so, and extracted a bit of torn yellow linen on which
something was written in rusty letters. Inside this rag was a paper.

"Then he went on feebly, for he was growing weak: 'The paper has all
that is on the linen. It took me years to read. Listen: my ancestor, a
political refugee from Lisbon, and one of the first Portuguese who
landed on these shores, wrote that when he was dying on those mountains
which no white foot ever pressed before or since. His name was José da
Silvestra, and he lived three hundred years ago. His slave, who waited
for him on this side of the mountains, found him dead, and brought the
writing home to Delagoa. It has been in the family ever since, but none
have cared to read it, till at last I did. And I have lost my life over
it, but another may succeed, and become the richest man in the
world--the richest man in the world. Only give it to no one, senor; go
yourself!'

"Then he began to wander again, and in an hour it was all over.

"God rest him! he died very quietly, and I buried him deep, with big
boulders on his breast; so I do not think that the jackals can have dug
him up. And then I came away."

"Ay, but the document?" said Sir Henry, in a tone of deep interest.

"Yes, the document; what was in it?" added the captain.

"Well, gentlemen, if you like I will tell you. I have never showed it
to anybody yet except to a drunken old Portuguese trader who translated
it for me, and had forgotten all about it by the next morning. The
original rag is at my home in Durban, together with poor Dom José's
translation, but I have the English rendering in my pocket-book, and a
facsimile of the map, if it can be called a map. Here it is."

[Illustration: MAP]

  "I, José da Silvestra, who am now dying of hunger in the little
  cave where no snow is on the north side of the nipple of the
  southernmost of the two mountains I have named Sheba's Breasts,
  write this in the year 1590 with a cleft bone upon a remnant of my
  raiment, my blood being the ink. If my slave should find it when
  he comes, and should bring it to Delagoa, let my friend (name
  illegible) bring the matter to the knowledge of the king, that he
  may send an army which, if they live through the desert and the
  mountains, and can overcome the brave Kukuanes and their devilish
  arts, to which end many priests should be brought, will make him
  the richest king since Solomon. With my own eyes I have seen the
  countless diamonds stored in Solomon's treasure chamber behind the
  white Death; but through the treachery of Gagool the witch-finder
  I might bring nought away, scarcely my life. Let him who comes
  follow the map, and climb the snow of Sheba's left breast till he
  reaches the nipple, on the north side of which is the great road
  Solomon made, from whence three days' journey to the King's
  Palace. Let him kill Gagool. Pray for my soul. Farewell.

José da Silvestra."

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://dixit.ca/css/gmail.css' />
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='/Users/jay/Dropbox/web-design/custom-css/gmail.css' />

