* A belated happy birthday from all of us 
http://il6.picdn.net/shutterstock/videos/12743384/thumb/10.jpg 

Pujya Dada,

Pranam.

I am sorry I couldn't be there for your birthday, but I wanted to send you a note to wish you the best and let you know I was thinking of you.

I think I've told you before that one of my very earliest memories is of a day when I was 6 years old, living in Amravati, and being very excited because Babuji had told us that Dada was coming and bringing a gift for us. On a clear sunny day, we gathered in a field and watched with excitement as you flew overhead and dropped a parcel from the plane! We ran to open the parcel and were so happy to find a box of chocolates you had wrapped for us. 

I also have many happy memories from my childhood of you coming to visit us, with your beard and your "bush shirt." I remember in particular the time you brought me a model airplane kit made of balsa wood. 

I remember when I was in 9th grade, you lent me your camera so I could learn to take pictures. I also remember going with Chachaji to visit you in Bombay, in your flat up the hill in Andheri, and going sightseeing. And I remember my first time in the air, in a glider you'd arranged for me to ride in from Safdarjung airport. Years later, when I was studying in Chicago, I have happy memories of visiting you in Montreal. 

I believe that when I was a young man I was quite contrarian with you, but over the years, I have learned to appreciate you and respect you more and more.

Here's to you, in appreciation of all the wisdom I've learned from you over the years and all the happy memories we've shared. 

Wishing you a very happy birthday, from me, Sunjay, and Neil.

Madhu


* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='evite.css'/> 
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
