* Art and cocktails in Gramercy
http://i.imgur.com/LqCZavD.jpg 

As 2016 ascends toward its cruising altitude, I'm gathering some friends together for early cocktails this Friday to make sure you all ______ (fill in the blank, I need some suggestions). 

This time I'll be co-hosting with a friend, the brilliant Max Makewell, at his art studio in Gramercy. 

We'll be convening early, at 6:00pm, to toast the new year amid Max's spooky and mythic Rorschach-like paintings before disbanding again at 10:00pm to forge off into the weekend as solitary individuals once again. 

The house will offer light snacks and a festive menu of cold-weather cocktails to warm your seasonally-affected bones, including drinks of gin, mezcal, and moonshine. Your own civilian contributions of foodstuffs and booze are also welcome but by no means required. Do feel free too to invite friends.

Looking forward to seeing you all.

Until then!

Jay

*Where*: 30 East 22nd Street #4D New York NY 10010 \\
*Map*: \\
*When*: Friday, January 8, 2016, 6:00 - 10:00pm \\ 



* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://dixit.ca/css/email.css' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
 
