* Art and cocktails in Gramercy
http://i.imgur.com/LqCZavD.jpg 

As 2016 rouses from its slumber and begins to lurch forward into the new year, I thought I'd gather some friends together Friday evening for some cold-weather cocktails to warm our seasonally-affected bones. 

I'll be co-hosting this party with a friend, the brilliant Max Makewell, at his art studio in Gramercy, and we'll be convening early, at 6:00pm, to toast the new year amid Max's mythic Rorschach-like paintings before disbanding at 10:00pm to forge off into the weekend as individuals once again. 

The house will offer light snacks and a festive menu of cocktails of gin, mezcal, and moonshine. Your own civilian contributions of booze and foodstuffs are also welcome but by no means required. Please feel free to invite friends as well.

Looking forward to seeing you all.

Until then!

Jay

*Where*: 30 East 22nd Street #4D New York NY 10010 \\
*Map*: \\
*When*: Friday, January 8, 2016, 6:00 - 10:00pm \\ 



* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://dixit.ca/css/email.css' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
 
