* Art and cocktails in Gramercy
http://i.imgur.com/UeJ0zq2.jpg 

As winter rouses and shakes off its slumber, I've decided to gather friends together on Friday some cold-weather cocktails to warm our bones and lift our seasonally-affected spirits. 

I'll be co-hosting with a friend, the brilliant Max Makewell, at his art studio in Gramercy, where we'll clink glasses amid his mythic, kaleidoscopic paintings and toast the possibilities of the year ahead. 

The house will offer light snacks and a festive menu of cocktails of gin, mezcal, and moonshine. Your own civilian contributions of booze and foodstuffs are also welcome but by no means required. Please feel free to invite friends as well.

We'll convene early, at 6:00pm, 

Looking forward to seeing you all.

Until then!

Jay

*Where*: 30 East 22nd Street #4D New York NY 10010 \\
*Map*: \\
*When*: Friday, January 8, 2016, 6:00 - 10:00pm \\ 



* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://dixit.ca/css/evite.css' />
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='/Users/jay/Dropbox/web-design/custom-css/evite.css' /> 
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
 
