#+TITLE: Merry Christmas
#+AUTHOR: Jay Dixit

#+BEGIN_HTML
<div class="initial_prompt">
<h1 class="begin">Type <strong>T</strong> to begin the slideshow.</h1>
</div>
#+END_HTML


* Merry Christmas!                                                    :slide: 
*Dear Neil*, \\
*Merry Christmas!* \\ 
*Love*, \\ 
*Sunjay*

Press right arrow to continue
→ 

* Merry Christmas!                                                    :slide: 
http://www.magic4walls.com/wp-content/uploads/2014/12/christmas-reindeer-Santa-Claus-new-year-2015-vector-New-York-desktop.jpg 

* Merry Christmas!                                                    :slide:
http://christmascardsayingss.com/wp-content/uploads/2015/11/Merry-Christmas-Photos.jpg 

* Merry Christmas!                                                    :slide:
http://orig13.deviantart.net/7e42/f/2012/346/4/1/rockefeller_center_tree_ny_2012_by_paws720-d5nv51r.jpg 

* Merry Christmas!                                                    :slide:

http://www.christmaseve-2015.com/wp-content/uploads/2015/12/Merry-Christmas-And-Happy-New-Year-Wallpaper-1.jpg 

* Merry Christmas!                                                    :slide:
http://i.imgur.com/EJq7gSp.jpg 


* Christmas Present :slide: 
http://images4.fanpop.com/image/photos/22200000/Christmas-gifts-christmas-gifts-22231228-2048-2048.jpg 

* Shoes :slide: 
http://www.wufashion.com/wp-content/uploads/2014/12/leather-shoes-5.jpg 


* Sneakers                                                            :slide: 
https://dobetter.files.wordpress.com/2008/06/running-shoes-sm.jpg 


* Question and answer :slide:

#+BEGIN_HTML
<embed src="3.pdf" Width="800px" height="2100px"> 
#+END_HTML 


* Sneaker advice                                                      :slide:

#+BEGIN_HTML
<embed src="2.pdf" Width="800px" height="2100px"> 
#+END_HTML 


* Merry Christmas *→*                                                 :slide: 
http://www.magic4walls.com/wp-content/uploads/2014/12/christmas-reindeer-Santa-Claus-new-year-2015-vector-New-York-desktop.jpg 


* Killshot:slide:

Introduced some 30 years ago, the original Killshot rolled out as low-profile tennis shoes. To give it our own spin, we updated the upper with sleek leather and suede and cast it in exclusive colors for some serious one-of-a-kind appeal.

- Leather, suede upper. 
- Cotton laces.
- Padded footbed.
- Natural gum rubber sole.
- Import.


* Nike Killshot 2 :slide: 
file:img/85231_WT0002.jpeg 


* Scroll down using trackpad :slide: 
file:img/85231_WT0002_d1.jpeg 

*→* 

* Click through the gallery below :slide:

#+BEGIN_HTML
<a class="embedly-card" data-card-key="5a5f778983654664b58c992abf623e2c" data-card-controls="0" data-card-theme="dark" data-card-width="600" href="http://imgur.com/gallery/X5Z5q">Killshot</a>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script> 
#+END_HTML 


** The End                                                            :slide:

* If you don't like them there's also these :slide: 
http://refreshstyle.com/blog/wp-content/uploads/2015/05/the-drop-date-adidas-stan-smith-otf.jpg 

#+OPTIONS: num:nil toc:nil tags:t

#+TAGS: slide(is )

#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../assets/org-html-slideshow/src/css/common.css" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../assets/org-html-slideshow/src/css/screen.css" media="screen" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../assets/org-html-slideshow/src/css/projection.css" media="projection" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../assets/org-html-slideshow/src/css/presenter.css" media="presenter" />
#+HTML_HEAD_EXTRA: <link rel="stylesheet" type="text/css" href="../assets/org-html-slideshow/src/css/jay-org-slideshow.css"/>



#+BEGIN_HTML
<script type="text/javascript" src="../assets/org-html-slideshow/production/org-html-slideshow.js"></script>

<script async src="http://cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script> 
#+END_HTML

# Local Variables:
# org-html-head-include-default-style: nil
# org-html-head-include-scripts: nil
# buffer-file-coding-system: utf-8-unix
# End:

