* The Defense 
#+BEGIN_EXPORT HTML
<div class="jayvideo">
<video autoplay loop class="center" src="dissertation.mp4" controls preload="auto" height="400" ></video></div> 
#+END_EXPORT 

Amici,

After two years, 160 pages, and 182 citations, Mia has successfully defended her dissertation proposal against those who would seek to destroy it. In recognition of her tireless investigations into readings of femininity in pop culture among adolescent girls, please join me and an assemblage of other well-wishers who wanted to be there but couldn't. Together we will witness Mia's passage from student to scholar. Amid wine and cheese, we'll stage a live 10-minute reenactment of The Defense, to be followed by a brief Q&A with the philosopher herself, to be followed in turn by fun. [[mailto:sunjaydixit@gmail.com][RSVP]] if you can make it.

Looking forward to seeing you all. 

Until then!

Jay

*Where*: [[https://goo.gl/maps/deaqUaSuWNA2][22 Saint Marks Place Apt. D New York NY 10003]] \\
*Map*: https://goo.gl/maps/deaqUaSuWNA2 \\
*When*: 3:00pm Saturday \\
*RSVP*: [[mailto:sunjaydixit@gmail.com][RSVP]] \\ 

http://derp.co.uk/xkcd/comics/thesis_defense.png 

#+BEGIN_EXPORT HTML 
<audio autoplay class="center" src="westworld.mp3" controls preload></audio>
#+END_EXPORT

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='http://dixit.ca/css/evite.css' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
 
