(TeX-add-style-hook
 "presentation"
 (lambda ()
   (TeX-add-to-alist 'LaTeX-provided-class-options
                     '(("article" "11pt")))
   (TeX-add-to-alist 'LaTeX-provided-package-options
                     '(("inputenc" "utf8") ("fontenc" "T1") ("ulem" "normalem") ("babel" "English")))
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "latex2e"
    "article"
    "art11"
    "inputenc"
    "fontenc"
    "fixltx2e"
    "graphicx"
    "grffile"
    "longtable"
    "wrapfig"
    "rotating"
    "ulem"
    "amsmath"
    "textcomp"
    "amssymb"
    "capt-of"
    "hyperref"
    "babel")
   (LaTeX-add-labels
    "sec:orgheadline1"
    "sec:orgheadline3"
    "sec:orgheadline2"
    "sec:orgheadline5"
    "sec:orgheadline4"
    "sec:orgheadline7"
    "sec:orgheadline6"
    "sec:orgheadline8"
    "sec:orgheadline9"
    "sec:orgheadline10"
    "sec:orgheadline11"
    "sec:orgheadline12"
    "sec:orgheadline13"
    "sec:orgheadline14"
    "sec:orgheadline15"
    "sec:orgheadline16"
    "sec:orgheadline18"
    "sec:orgheadline17"
    "sec:orgheadline20"
    "sec:orgheadline19"
    "sec:orgheadline22"
    "sec:orgheadline21"
    "sec:orgheadline24"
    "sec:orgheadline23"
    "sec:orgheadline26"
    "sec:orgheadline25"
    "sec:orgheadline28"
    "sec:orgheadline27"
    "sec:orgheadline30"
    "sec:orgheadline29"
    "sec:orgheadline32"
    "sec:orgheadline31"
    "sec:orgheadline33"
    "sec:orgheadline34"
    "sec:orgheadline35"
    "sec:orgheadline36"
    "sec:orgheadline38"
    "sec:orgheadline37"
    "sec:orgheadline39"
    "sec:orgheadline40"
    "sec:orgheadline42"
    "sec:orgheadline41"
    "sec:orgheadline43"
    "sec:orgheadline44"
    "sec:orgheadline45"
    "sec:orgheadline46"
    "sec:orgheadline59"
    "sec:orgheadline47"
    "sec:orgheadline48"
    "sec:orgheadline49"
    "sec:orgheadline56"
    "sec:orgheadline53"
    "sec:orgheadline52"
    "sec:orgheadline50"
    "sec:orgheadline51"
    "sec:orgheadline55"
    "sec:orgheadline54"
    "sec:orgheadline58"
    "sec:orgheadline57"
    "sec:orgheadline62"
    "sec:orgheadline61"
    "sec:orgheadline60"
    "sec:orgheadline65"
    "sec:orgheadline63"
    "sec:orgheadline64"
    "sec:orgheadline67"
    "sec:orgheadline66"
    "sec:orgheadline69"
    "sec:orgheadline68"
    "sec:orgheadline72"
    "sec:orgheadline70"
    "sec:orgheadline71")))

