* Cocktails on Saint Marks
http://i4.mirror.co.uk/incoming/article6468441.ece/ALTERNATES/s615/asteroid-1-main.jpg 

As 2016 prepares to draw its final putrid breath, some among us find ourselves wishing we could celebrate together but priorly committed to separate parties for the stroke of midnight. In order that we might gather together as a family one last time before the great crossing over, we will convene here on Saint Marks Place at the unfashionably early hour of 5:00 o'clock to carouse and commune before adjourning promptly at 9:00 and scattering across the boroughs.

Take note, this is not a New Year's party but a mere prologue, a waystation to fortify you on your journey before I send you out into the night. In those early hours of evening, corks will be popped, champagne will be poured, and friends will be united. As the night wears on, bodies will be bumped, drinks will be spilled, and everyone will get a mug of mulled wine and a dollop of beef stew. 

The house will offer a limited menu of cocktails of rum, mezcal, and moonshine. Your own civilian contributions of wine and spirits are also welcome, as are your friends.

In these uncertain times, let us celebrate the blessings we have and raise a glass to friendship, good cheer, and better times ahead.

Looking forward to seeing you all. 

Until then!

Jay

*Where*: [[https://goo.gl/maps/deaqUaSuWNA2][22 Saint Marks Place Apt. D New York NY 10003]] \\
*Map*: https://goo.gl/maps/deaqUaSuWNA2 \\
*When*: Friday December 31, 2016, 5:00pm. \\
*Friends*: Welcome. 
*RSVP*: [[mailto:jay@newyorkwritersintensive.com][jay@newyorkwritersintensive.com]] 

#+BEGIN_EXPORT HTML 
<audio autoplay class="center" src="aforest.mp3" controls preload></audio>
#+END_EXPORT

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='thedefense.css' />
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
 
