* Cocktails on Saint Marks
:PROPERTIES:
:SENT-ON:  Fri Dec 30 15:38:25 2016
:TO:       sunjaydixit@gmail.com
:END:
/Users/jay/Dropbox/github/incandescentman.github.io/newyears/party-as-the-world-burns.jpg 

As 2016 prepares to draw its final putrid breath, some among us find ourselves wishing to celebrate together but priorly committed to separate parties for the stroke of midnight. In order that we might gather together as a family one last time before the great crossing over, we will convene here on Saint Marks Place at the unfashionably early hour of 5:00 o'clock to carouse and commune before adjourning promptly at 9:00 and scattering across the boroughs.

Take note, this party is but a prologue, a waystation to fortify you on your journey before I send you out into the night. Corks will be popped, champagne will be poured, and friends will be united. Before long, bodies will be bumped, drinks will be spilled, and everyone will get a mug of mulled wine and a dollop of beef stew. 

The house will offer a limited menu of cocktails of rum, mezcal, and moonshine. Your own civilian contributions of wine and spirits are welcome, as are friends.

In these uncertain times, let us acknowledge our good fortune and raise a glass to friendship, good cheer, and better days ahead.

Looking forward to seeing you all. Until then!

Jay

*When*: Saturday December 31, 2016, 5:00pm - 9:00pm \\
*Where*: [[https://goo.gl/maps/deaqUaSuWNA2][22 Saint Marks Place Apt. D New York NY 10003]] \\
*Map*: https://goo.gl/maps/deaqUaSuWNA2 \\
*Friends*: Welcome \\ 
*RSVP*: [[mailto:jay@newyorkwritersintensive.com][jay@newyorkwritersintensive.com]] 

#+BEGIN_EXPORT HTML 
<audio autoplay class="center" src="aforest.mp3" controls preload></audio>
#+END_EXPORT

* export settings                                          :ARCHIVE:noexport:
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='thedefense.css' />
#+HTML_HEAD: <meta property="og:title" content="Cocktails on Saint Marks" /> 
#+HTML_HEAD: <meta property="og:url" content="http://dixit.ca/newyears/" /> 
#+HTML_HEAD: <meta property="og:image" content="party-as-the-world-burns.jpg"/> 
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t -:t f:t *:t <:t
