#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='css/style.css' /> 
#+HTML_HEAD: <link rel='stylesheet' type='text/css' href='css/content.css' /> 
#+HTML_HEAD: <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script> 
#+HTML_HEAD: <script src="js/index.js"></script> 
#+OPTIONS:   H:6 num:nil toc:nil :nil @:t ::t |:t ^:t-:t f:t *:t <:t

#+BEGIN_HTML
<div id="scroll-animate">
  <div id="scroll-animate-main">
    <div class="wrapper-parallax">
      <header>
        <h1>Header</h1>
      </header> 
      <section class="content">
#+END_HTML 
* Heading 1
I was born a gentleman, though I have been nothing but a
poor traveling trader and hunter all my life. Whether I have remained
so I know not, you must judge of that. Heaven knows I've tried. I have
killed many men in my time, yet I have never slain wantonly or stained
my hand in innocent blood, but only in self-defence. The Almighty gave
us our lives, and I suppose He meant us to defend them, at least I have
always acted on that, and I hope it will not be brought up against me
when my clock strikes. There, there, it is a cruel and a wicked world,
and for a timid man I have been mixed up in a great deal of fighting. I
cannot tell the rights of it, but at any rate I have never stolen,
though once I cheated a Kafir out of a herd of cattle. But then he had
done me a dirty turn, and it has troubled me ever since into the
bargain.


Well, it is eighteen months or so ago since first I met Sir Henry
Curtis and Captain Good. It was in this way. I had been up elephant
hunting beyond Bamangwato, and had met with bad luck. Everything went
wrong that trip, and to top up with I got the fever badly. So soon as I
was well enough I trekked down to the Diamond Fields, sold such ivory
as I had, together with my wagon and oxen, discharged my hunters, and
took the post-cart to the Cape. After spending a week in Cape Town,
finding that they overcharged me at the hotel, and having seen
everything there was to see, including the botanical gardens, which
seem to me likely to confer a great benefit on the country, and the new
Houses of Parliament, which I expect will do nothing of the sort, I
determined to go back to Natal by the _Dunkeld_, then lying at the
docks waiting for the _Edinburgh Castle_ due in from England. I took my
berth and went aboard, and that afternoon the Natal passengers from the
_Edinburgh Castle_ transhipped, and we weighed and put to sea.

Among these passengers who came on board were two who excited my
curiosity. One, a gentleman of about thirty, was perhaps the
biggest-chested and longest-armed man I ever saw. He had yellow hair, a
thick yellow beard, clear-cut features, and large grey eyes set deep in
his head. I never saw a finer-looking man, and somehow he reminded me
of an ancient Dane. Not that I know much of ancient Danes, though I
knew a modern Dane who did me out of ten pounds; but I remember once
seeing a picture of some of those gentry, who, I take it, were a kind
of white Zulus. They were drinking out of big horns, and their long
hair hung down their backs. As I looked at my friend standing there by
the companion-ladder, I thought that if he only let his grow a little,
put one of those chain shirts on to his great shoulders, and took hold
of a battle-axe and a horn mug, he might have sat as a model for that
picture. And by the way it is a curious thing, and just shows how the
blood will out, I discovered afterwards that Sir Henry Curtis, for that
was the big man's name, is of Danish blood. He also reminded me
strongly of somebody else, but at the time I could not remember who it
was. 
#+BEGIN_HTML
</section>

      <footer>
        <h1>Footer</h1>
      </footer>
    </div>
  </div>
</div> 
#+END_HTML 
